base_url = " https://agourlay.github.io"

title = "Arnaud Gourlay's blog"
description = "Yet another programming blog"

generate_feed = true

compile_sass = true

build_search_index = false

theme = "anpu"

taxonomies = [
    { name = "categories" },
    { name = "tags" },
]

[markdown]
highlight_code = true

[extra]
anpu_menu_links = [
    { url = "$BASE_URL/tags/", name = "Tags" },
    { url = "/pages/about", name = "About" },
]
